[package]
name = "highwater-control"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
base64.workspace = true
bytes.workspace = true
percent-encoding.workspace = true
reqwest.workspace = true
tokio.workspace = true
